version: '2.4'

services:
  jenkins:
    image: jenkins/jenkins:latest
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: -Xms1g -Xmx1g


  update-json-resigner:
#    image: kruft/jenkins-update-dot-json-resigner:1.0
    build:
      context: .
    volumes:
      - ./cert:/cert/
    environment:
      DEBUG: "true"

      LISTEN_PORT: 8282

#      LISTEN_PORT: 8443
#      TLS_CERT_PATH: "/cert/your-update-center.crt"
#      TLS_KEY_PATH: "/cert/your-update-center.key"

      UPDATE_JSON_URL: http://updates.jenkins.io/update-center.json

      UPDATE_JSON_DOWNLOAD_TIMEOUT: 90s

      UPDATE_JSON_CACHE_TTL: 30m

      ORIGIN_DOWNLOAD_URL: http://updates.jenkins-ci.org/download/
      NEW_DOWNLOAD_URL: http://ftp-nyc.osuosl.org/pub/jenkins/

      SIGN_CERTIFICATE_PATH: /cert/your-update-center.crt
      SIGN_KEY_PATH: /cert/your-update-center.key
    ports:
      - "8282:8282"
#      - "8443:8443"
