version: '2.4'

services:
  jenkins:
    image: jenkins/jenkins:latest
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: -Xms1g -Xmx1g

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx_home/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_home/www:/usr/share/nginx/html
    ports:
      - "80:80"
