name: "current/update-center.json compatibility check"

on:
  schedule:
    - cron: "30 3 * * *"

jobs:
  compatibility-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Test with the Go CLI
        run: go test -v ./internal/jenkins
