name: Master Build

on:
  push:
    branches: [ master ]
#    paths:
#      - '.github/workflows/master-build.yml'
  pull_request:
    branches: [ master ]

jobs:
  master-build:
    #    name: build the app and image
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: kruft/jenkins-update-dot-json-resigner

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

#      - name: Test
#        run: go test -v ./internal/kubernetes/...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login in Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${DOCKER_IMAGE}:latest:latest
            ghcr.io/${GITHUB_REPOSITORY}:latest
          cache-from: type=registry,ref=ghcr.io/${GITHUB_REPOSITORY}:latest
          cache-to: type=inline

#      - name: Build the Docker image
#        run: docker build . --file Dockerfile --tag ${DOCKER_IMAGE}:latest

#      - name: Login in Docker registry
#        run: docker login -u"${DOCKER_REGISTRY_USER}" -p"${DOCKER_REGISTRY_TOKEN}"

#      - name: Push Docker image to registry
#        run: docker push ${DOCKER_IMAGE}:latest
